export type ArticleLocale = {
  title: string;
  description: string;
  answer: string[];
  sections: { heading: string; paragraphs: string[] }[];
};

export type Article = { slug: string; en: ArticleLocale; sv: ArticleLocale };

export const articles: Article[] = [
  {
    slug: 'identify-requirements-in-construction-tenders',
    en: { title: 'How calculation teams can identify requirements across a construction tender', description: 'A practical method for finding, classifying, and assigning construction-tender requirements.', answer: ['Calculation teams should read tender material as a connected set of sources, not as isolated files. Start with a shared register, capture each requirement with its source reference, then assign review responsibility before pricing or commitments are made.'], sections: [{ heading: 'Build one review map', paragraphs: ['List every tender document, drawing, appendix, clarification, and referenced standard before review begins.', 'Use the same categories across the team: scope, technical solution, documentation, commercial terms, safety, quality, and delivery.'] }, { heading: 'Capture the source with the requirement', paragraphs: ['Record the exact document, revision, page, section, and clause for every entry.', 'A source reference lets a reviewer verify the wording quickly when a question or conflict appears.'] }, { heading: 'Turn findings into decisions', paragraphs: ['Give each requirement an owner and a clear status such as open, confirmed, assumed, or excluded.', 'The register should support calculation decisions rather than becoming a passive list of notes.'] }] },
    sv: { title: 'Så identifierar kalkylteam krav i ett bygganbud', description: 'En praktisk metod för att hitta, klassificera och fördela krav i bygganbud.', answer: ['Kalkylteam bör läsa anbudsmaterialet som en sammanhängande helhet, inte som enskilda filer. Börja med ett gemensamt register, koppla varje krav till sin källa och fördela granskningen innan pris eller åtaganden fastställs.'], sections: [{ heading: 'Skapa en gemensam granskningskarta', paragraphs: ['Lista alla anbudshandlingar, ritningar, bilagor, förtydliganden och hänvisade standarder innan granskningen börjar.', 'Använd samma kategorier i teamet: omfattning, teknik, dokumentation, kommersiella villkor, säkerhet, kvalitet och leverans.'] }, { heading: 'Spara källan tillsammans med kravet', paragraphs: ['Registrera dokument, revision, sida, avsnitt och klausul för varje krav.', 'Källhänvisningen gör det enkelt att kontrollera formuleringen när frågor eller konflikter uppstår.'] }, { heading: 'Gör iakttagelser till beslut', paragraphs: ['Ge varje krav en ansvarig och en tydlig status, till exempel öppet, bekräftat, antaget eller undantaget.', 'Registret ska stödja kalkylbeslut, inte bli en passiv lista med anteckningar.'] }] },
  },
  {
    slug: 'tender-requirements-versus-contract-requirements',
    en: { title: 'Tender requirements versus contract requirements: what should be tracked?', description: 'Understand which tender requirements should be tracked into the contract and delivery phases.', answer: ['Track requirements that affect scope, price, risk, evidence, or delivery responsibility from tender through contract. Keep the tender source and the agreed contractual wording side by side so the team can see what changed before work starts.'], sections: [{ heading: 'Keep the two states distinct', paragraphs: ['Tender requirements describe what was requested; contract requirements describe what was agreed.', 'A requirement may be clarified, qualified, replaced, or excluded during negotiation, so neither state should overwrite the other.'] }, { heading: 'Track the change path', paragraphs: ['Link clarifications, reservations, amendments, and contract clauses to the original tender requirement.', 'This creates an auditable decision trail for project, commercial, and site teams.'] }, { heading: 'Carry forward operational obligations', paragraphs: ['Identify obligations that need proof during delivery, such as approvals, documentation, tests, and handovers.', 'Assign them before the project team receives the final requirement set.'] }] },
    sv: { title: 'Anbudskrav och kontraktskrav: vad ska följas upp?', description: 'Förstå vilka anbudskrav som ska följas från anbud till kontrakt och leverans.', answer: ['Krav som påverkar omfattning, pris, risk, bevisning eller leveransansvar bör följas från anbud till kontrakt. Behåll anbudskällan och den överenskomna kontraktstexten sida vid sida så att ändringar syns innan projektet startar.'], sections: [{ heading: 'Håll de två lägena isär', paragraphs: ['Anbudskrav beskriver vad som efterfrågades, medan kontraktskrav beskriver vad som avtalades.', 'Ett krav kan förtydligas, villkoras, ersättas eller undantas under förhandlingen.'] }, { heading: 'Följ ändringskedjan', paragraphs: ['Koppla förtydliganden, reservationer, ändringar och kontraktsklausuler till det ursprungliga anbudskravet.', 'Det ger en spårbar beslutskedja för projekt-, kommersiella och produktionsroller.'] }, { heading: 'För vidare operativa skyldigheter', paragraphs: ['Identifiera skyldigheter som kräver bevis under leveransen, exempelvis godkännanden, dokumentation, provning och överlämning.', 'Fördela ansvaret innan projektteamet tar över det slutliga kravunderlaget.'] }] },
  },
  {
    slug: 'trace-requirements-to-original-source',
    en: { title: 'How to trace a project requirement back to its original source', description: 'A source-traceability method for project requirements in construction documentation.', answer: ['Every project requirement should retain a direct link to the document and wording that created it. Store the source reference, revision, and any decision that changed the interpretation so a reviewer can reproduce the reasoning.'], sections: [{ heading: 'Use a precise source reference', paragraphs: ['Capture the document title, revision, page, section, clause, and relevant drawing reference.', 'Avoid references such as “specification” or “client document”; they are too broad to verify.'] }, { heading: 'Preserve interpretation', paragraphs: ['Record why the team interpreted a clause in a particular way and who confirmed it.', 'Link clarification answers and meeting decisions rather than copying them into a free-text note.'] }, { heading: 'Review traceability at handover', paragraphs: ['Before handover, test a sample of important requirements by following each one back to its source.', 'Missing links reveal where assumptions have replaced evidence.'] }] },
    sv: { title: 'Så spårar du ett projektkrav till dess ursprungliga källa', description: 'En metod för källspårbarhet i byggprojektets kravdokumentation.', answer: ['Varje projektkrav bör behålla en direkt länk till dokumentet och formuleringen som skapade det. Spara källhänvisning, revision och beslut som ändrat tolkningen så att resonemanget kan återskapas.'], sections: [{ heading: 'Använd en exakt källhänvisning', paragraphs: ['Registrera dokumenttitel, revision, sida, avsnitt, klausul och relevant ritningshänvisning.', 'Hänvisningar som “specifikation” eller “beställardokument” är för breda för att kunna verifieras.'] }, { heading: 'Bevara tolkningen', paragraphs: ['Notera varför teamet tolkat en klausul på ett visst sätt och vem som bekräftat den.', 'Länka svar på förtydliganden och mötesbeslut i stället för att kopiera dem som fria anteckningar.'] }, { heading: 'Kontrollera spårbarheten vid överlämning', paragraphs: ['Följ ett urval av viktiga krav tillbaka till sin källa före överlämning.', 'Saknade länkar visar var antaganden har ersatt bevis.'] }] },
  },
  {
    slug: 'manage-amendments-conflicts-and-clarifications',
    en: { title: 'Managing amendments, conflicts, and clarifications in tender documentation', description: 'A controlled approach to tender amendments, document conflicts, and clarifications.', answer: ['Treat amendments, conflicts, and clarifications as changes to the requirement record, not as separate email traffic. Link each item to the affected requirement, record the decision owner, and make the latest valid position visible to the whole team.'], sections: [{ heading: 'Register changes as they arrive', paragraphs: ['Log an amendment or clarification immediately, including its issue date and affected documents.', 'Do not rely on reviewers remembering which version was current.'] }, { heading: 'Expose conflicts', paragraphs: ['When documents conflict, create a visible issue instead of silently choosing one wording.', 'State the competing sources, the impact, the proposed interpretation, and the required decision.'] }, { heading: 'Freeze the tender view', paragraphs: ['Before submission, confirm the applicable revisions and unresolved questions.', 'Keep the frozen tender view available when the contract and delivery teams take over.'] }] },
    sv: { title: 'Hantera ändringar, konflikter och förtydliganden i anbudshandlingar', description: 'Ett kontrollerat arbetssätt för ändringar, dokumentkonflikter och förtydliganden.', answer: ['Hantera ändringar, konflikter och förtydliganden som uppdateringar av kravposten, inte som fristående e-posttrafik. Koppla varje händelse till berört krav, registrera beslutsansvar och visa den senaste giltiga positionen för hela teamet.'], sections: [{ heading: 'Registrera ändringar när de kommer', paragraphs: ['Logga ändringar och förtydliganden direkt med datum och berörda dokument.', 'Lita inte på att granskare minns vilken version som gäller.'] }, { heading: 'Synliggör konflikter', paragraphs: ['När dokument motsäger varandra ska en synlig fråga skapas i stället för att en formulering väljs tyst.', 'Beskriv källorna, påverkan, föreslagen tolkning och vilket beslut som krävs.'] }, { heading: 'Frys anbudsläget', paragraphs: ['Bekräfta gällande revisioner och olösta frågor före inlämning.', 'Behåll den frysta anbudsvyn när kontrakts- och projektteamet tar över.'] }] },
  },
  {
    slug: 'requirements-register-before-tender-submission',
    en: { title: 'What a requirements register should contain before tender submission', description: 'The essential fields for a tender requirements register before submission.', answer: ['Before submission, a requirements register should show the requirement, its source, status, owner, commercial or delivery impact, and the decision behind the planned response. It should make unresolved matters visible rather than hiding them in individual files.'], sections: [{ heading: 'Core fields', paragraphs: ['Include an identifier, requirement text, source reference, category, owner, and status.', 'Use a consistent status model so reviewers understand what still needs action.'] }, { heading: 'Decision fields', paragraphs: ['Capture the proposed response, assumptions, exclusions, and links to clarifications.', 'Record the reason for each material decision so it can be reviewed later.'] }, { heading: 'Submission review', paragraphs: ['Review open and high-impact entries as a team before submission.', 'Freeze the register together with the final tender package.'] }] },
    sv: { title: 'Vad ett kravregister bör innehålla före anbudsinlämning', description: 'Viktiga fält i ett kravregister före anbudsinlämning.', answer: ['Före inlämning bör ett kravregister visa kravet, dess källa, status, ansvarig, kommersiell eller produktionsmässig påverkan samt beslutet bakom det planerade svaret. Det ska synliggöra olösta frågor i stället för att gömma dem i enskilda filer.'], sections: [{ heading: 'Grundfält', paragraphs: ['Inkludera identifierare, kravtext, källhänvisning, kategori, ansvarig och status.', 'Använd en enhetlig statusmodell så att granskarna ser vad som återstår.'] }, { heading: 'Beslutsfält', paragraphs: ['Spara planerat svar, antaganden, undantag och länkar till förtydliganden.', 'Registrera skälet till varje väsentligt beslut så att det kan granskas senare.'] }, { heading: 'Granskning före inlämning', paragraphs: ['Granska öppna och betydelsefulla poster tillsammans före inlämning.', 'Frys registret tillsammans med det slutliga anbudspaketet.'] }] },
  },
  {
    slug: 'carry-tender-requirements-into-delivery',
    en: { title: 'How construction leaders can carry tender requirements into delivery', description: 'A handover method for moving tender requirements into project delivery.', answer: ['Construction leaders should hand over a verified requirement set, its sources, open decisions, and named owners before delivery begins. This makes tender commitments operational rather than leaving them in the bid archive.'], sections: [{ heading: 'Prepare a delivery-ready handover', paragraphs: ['Separate agreed obligations from tender assumptions and unresolved questions.', 'Include source links and the evidence or milestones needed to demonstrate compliance.'] }, { heading: 'Assign ownership', paragraphs: ['Map requirements to design, procurement, production, quality, and commercial roles.', 'An owner should know both the action required and the proof expected.'] }, { heading: 'Maintain change control', paragraphs: ['Keep the same register active when project changes are introduced.', 'New decisions should remain linked to their original obligation.'] }] },
    sv: { title: 'Så för byggledare över anbudskrav till produktion', description: 'En överlämningsmetod för att föra anbudskrav in i projektleveransen.', answer: ['Byggledare bör överlämna ett verifierat kravunderlag med källor, öppna beslut och namngivna ansvariga innan produktionen börjar. Då blir anbudsåtaganden operativa i stället för att ligga kvar i anbudsarkivet.'], sections: [{ heading: 'Förbered en leveransklar överlämning', paragraphs: ['Separera avtalade skyldigheter från anbudsantaganden och olösta frågor.', 'Inkludera källänkar samt bevis eller milstolpar som visar efterlevnad.'] }, { heading: 'Fördela ägarskap', paragraphs: ['Koppla krav till roller inom projektering, inköp, produktion, kvalitet och kommersiellt ansvar.', 'En ansvarig ska förstå både åtgärden och vilket bevis som förväntas.'] }, { heading: 'Behåll ändringskontrollen', paragraphs: ['Låt samma register vara aktivt när projektändringar införs.', 'Nya beslut ska fortsatt vara länkade till den ursprungliga skyldigheten.'] }] },
  },
  {
    slug: 'ownership-of-requirement-decisions',
    en: { title: 'Who should own requirement decisions across calculation, tender, design, and site teams?', description: 'A role-based model for requirement decisions across construction teams.', answer: ['Requirement decisions need a named owner at each stage, while the original source and decision trail remain shared. Ownership should follow the decision being made, not simply the team that first found the requirement.'], sections: [{ heading: 'Give every decision an owner', paragraphs: ['Calculation owns pricing assumptions, commercial roles own reservations, and technical roles own solution interpretation.', 'Cross-functional questions need one accountable decision maker and recorded contributors.'] }, { heading: 'Keep shared visibility', paragraphs: ['Teams need one current view of requirement status and source material.', 'Shared visibility prevents handover from becoming a transfer of undocumented assumptions.'] }, { heading: 'Escalate early', paragraphs: ['Define when uncertainty must be escalated to the client, project lead, or commercial authority.', 'A visible escalation route is safer than informal agreement.'] }] },
    sv: { title: 'Vem ska äga kravbeslut mellan kalkyl, anbud, projektering och plats?', description: 'En rollbaserad modell för kravbeslut mellan byggprojektets team.', answer: ['Kravbeslut behöver en namngiven ansvarig i varje skede, samtidigt som källa och beslutskedja är gemensamma. Ägarskapet bör följa beslutet som fattas, inte bara teamet som först hittade kravet.'], sections: [{ heading: 'Ge varje beslut en ansvarig', paragraphs: ['Kalkyl ansvarar för prisantaganden, kommersiella roller för reservationer och tekniska roller för lösningstolkning.', 'Tvärfunktionella frågor behöver en ansvarig beslutsfattare och dokumenterade bidragsgivare.'] }, { heading: 'Behåll gemensam insyn', paragraphs: ['Team behöver en gemensam aktuell bild av kravstatus och källmaterial.', 'Gemensam insyn förhindrar att överlämningen blir en överföring av odokumenterade antaganden.'] }, { heading: 'Eskalera tidigt', paragraphs: ['Definiera när osäkerhet ska lyftas till beställare, projektledning eller kommersiell beslutsnivå.', 'En tydlig eskaleringsväg är säkrare än informella överenskommelser.'] }] },
  },
  {
    slug: 'audit-tender-documents-at-scale',
    en: { title: 'Why tender documents are difficult to audit at scale', description: 'Why large tender-document sets are difficult to review consistently and traceably.', answer: ['Tender documents are difficult to audit at scale because requirements are spread across formats, revisions, references, and overlapping responsibilities. A structured register and source traceability make review repeatable without relying on individual memory.'], sections: [{ heading: 'Information is distributed', paragraphs: ['Requirements may sit in specifications, drawings, schedules, appendices, and clarification notices.', 'References to external standards add another layer of review.'] }, { heading: 'Documents change', paragraphs: ['Revisions and clarifications can alter the meaning of an earlier requirement.', 'Without a linked change history, teams may act on an outdated interpretation.'] }, { heading: 'Review needs structure', paragraphs: ['A shared workflow, ownership, and traceable source references create consistent review across a large set.', 'The goal is not merely to find text, but to turn it into accountable decisions.'] }] },
    sv: { title: 'Varför anbudshandlingar är svåra att granska i stor skala', description: 'Varför stora mängder anbudshandlingar är svåra att granska konsekvent och spårbart.', answer: ['Anbudshandlingar är svåra att granska i stor skala eftersom krav är spridda över format, revisioner, hänvisningar och överlappande ansvar. Ett strukturerat register och källspårbarhet gör granskningen repeterbar utan att förlita sig på enskilda personers minne.'], sections: [{ heading: 'Informationen är spridd', paragraphs: ['Krav kan finnas i beskrivningar, ritningar, tidplaner, bilagor och förtydliganden.', 'Hänvisningar till externa standarder lägger till ytterligare ett granskningslager.'] }, { heading: 'Dokument ändras', paragraphs: ['Revisioner och förtydliganden kan ändra innebörden av ett tidigare krav.', 'Utan länkad ändringshistorik kan team agera på en gammal tolkning.'] }, { heading: 'Granskning behöver struktur', paragraphs: ['Ett gemensamt arbetssätt, ägarskap och spårbara källhänvisningar ger konsekvent granskning i stora underlag.', 'Målet är inte bara att hitta text utan att göra den till ansvariga beslut.'] }] },
  },
];

export const getArticle = (slug: string) => articles.find((article) => article.slug === slug);
